# Generated by Django 5.2.3 on 2025-06-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ingredients_processed',
            field=models.BooleanField(default=False, verbose_name='Ингредиенты списаны'),
        ),
    ]
