# Generated by Django 5.2.3 on 2025-06-18 23:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ингредиента')),
                ('unit', models.CharField(default='г', max_length=20, verbose_name='Единица измерения')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость за единицу')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Категория меню', 'verbose_name_plural': 'Категории меню'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'sort_order', 'name'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Изображение категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Калории'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Себестоимость'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярное'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_spicy',
            field=models.BooleanField(default=False, verbose_name='Острое'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_vegetarian',
            field=models.BooleanField(default=False, verbose_name='Вегетарианское'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='preparation_time',
            field=models.PositiveIntegerField(default=15, verbose_name='Время приготовления (мин)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес (г)'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Количество')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Примечания')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='menu.menuitem')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ingredient')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'unique_together': {('dish', 'ingredient')},
            },
        ),
    ]
