# Generated by Django 5.2.3 on 2025-06-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('кг', 'Килограммы'), ('г', 'Граммы'), ('л', 'Литры'), ('мл', 'Миллилитры'), ('шт', 'Штуки'), ('уп', 'Упаковки')], help_text='Единица измерения', max_length=20, verbose_name='Единица измерения'),
        ),
    ]
